website/urls.py
from django.conf.urls import url, include
from . import views


app_name = 'website'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^/contact', views.contact, name='contact'),
    url(r'^about', views.about, name='about'),
    url(r'^tours', views.tours, name='tours'),
    url(r'^destinations', views.destinations, name = 'destinations')
]

yakigroup/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', include('website.urls', namespace='home')),
    url(r'^website/', include('website.urls', namespace='website')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourmanager/models.py
from django.db import models
from django.contrib.auth.models import User


class Regions(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=30, blank=False)
    map_location = models.CharField(max_length=255, blank=True)
    region_featured_image = models.ImageField(upload_to='regions')


class Destinations(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    region = models.ForeignKey(Regions, on_delete=models.PROTECT)
    destination_name = models.CharField(max_length=30, blank=False)
    map_location = models.CharField(max_length=255, blank=True)
    destination_image = models.ImageField(upload_to='destinatiions')


class Tours(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    tour_name = models.CharField(max_length=30, blank=False)
    start_date = models.DateField(blank=False)
    end_date = models.DateField(blank=False)
    min_number_of_people = models.CharField(max_length=4, blank=False)
    max_number_of_people = models.CharField(max_length=4, blank=False)
    tour_price = models.FloatField(max_length=20, blank=False)


class TourData(models.Model):
    tourid = models.ForeignKey(Tours, on_delete=models.PROTECT)
    region = models.ForeignKey(Regions, on_delete=models.PROTECT)
    destination = models.ForeignKey(Destinations, on_delete=models.PROTECT)
    number_of_days = models.CharField(max_length=3, blank=True)

website/models.py
from django.db import models
from django.contrib.auth.models import User


class WebsiteContects(models.Model):
    websection = models.CharField(max_length=255, blank=True)
    heading1 = models.CharField(max_length=255, blank=True)
    heading2 = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    attachment_image = models.ImageField(upload_to='website/images', blank=True)
    attachment_file=models.FileField(upload_to='website/uploads', blank=True)
    datafeatured = models.CharField(max_length=255, blank=True)

tourmanager/views.py
from django.shortcuts import render

# Create your views here.

website/views.py
from django.http import HttpResponse
from django.shortcuts import render
from tourmanager.models import Destinations
from .models import WebsiteContects


def home(request):
    slider = WebsiteContects.objects.all().filter(websection='slider')
    slider = {'sliders': slider}
    return render(request, 'home.html', slider)


def contact(request):
    return render(request, 'contactus.html')


def about(request):
    return render(request, 'about.html')


def tours(request):
    return  render(request, 'tours.html')


def destinations(request):
    destination_list = Destinations.objects.all()
    destination_list = {'destinations': destination_list}
    return render(request, 'destinations.html', destination_list)

templates/webnav_templete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}  {% endblock %}</title>
	<link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Animate CSS -->
	<link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <!-- Venobox CSS -->
	<link href="{% static 'css/venobox.css' %}" rel="stylesheet">
	<!-- Font-awesome -->
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}">
	<!-- Flaticon -->
	<link rel="stylesheet" href="{% static 'fonts/flaticon/css/flaticon.css' %}">
	<!-- Google font-->
	<link href="{% static 'https://fonts.googleapis.com/css?family=Poppins:300,400,400i,500,600,700,800,900' %}" rel="stylesheet">
	<!-- Main CSS -->
	<link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>
	<!--Preload-->
	<div class="preloader">
		<div class="preloader_image">
			<div class="sk-double-bounce">
				<div class="sk-child sk-double-bounce1"></div>
				<div class="sk-child sk-double-bounce2"></div>
			</div>
		</div>
	</div>

	<nav class="navbar navbar-expand-lg bg-white">
		<div class="container">
			<a class="navbar-brand" href="index.html">
				<img src="{% static 'img/logo.png' %}" alt="Logo">
			</a>
			<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="main-nav">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'website:home' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'website:about' %}">About Us</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'website:tours' %}">Tours</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'website:destinations' %}">Destinations</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="gallery.html">Gallery</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'website:contact' %}">Contact Us</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<!-- end nav -->
        {% block main %} {% endblock %}

	<footer id="footer">
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<div class="footer-widget">
							<h3>About Us</h3>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>

						</div>
					</div>
					<div class="col-md-3">
						<div class="footer-widget">
							<h3>Quick Links</h3>
							<ul>
								<li><a href="about-us.html">About Us</a></li>
								<li><a href="tours.html">Tours</a></li>
								<li><a href="gallery.html">Gallery</a></li>
								<li><a href="contact-us.html">Contact Us</a></li>
							</ul>
						</div>
					</div>
					<div class="col-md-3">
						<div class="footer-widget">
							<h3>Contact Info</h3>
							<ul>
								<li><i class="fa fa-send" aria-hidden="true"></i> 3481 Rabana Place, 2090</li>
								<li><i class="fa fa-phone" aria-hidden="true"></i> +880 17980XXXXX</li>
								<li><i class="fa fa-envelope-o" aria-hidden="true"></i> info@example.com</li>
								<li><i class="fa fa-fax" aria-hidden="true"></i> Fax : 02 9635 0247</li>
							</ul>
						</div>
					</div>
					<div class="col-md-3">
						<div class="footer-widget">
							<h3>Business hour</h3>
							<ul class="bussiness-hour">
								<li>Monday-Friday: <span class="pull-right">9am - 5pm.</span></li>
								<li>Saturday: <span class="pull-right">10am - 2pm.</span></li>
								<li>Sunday: <span class="pull-right">Closed.</span></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<div class="col-sm-12 col-md-6">
						<div class="copyright">
							<p>Copyright &copy; 2018. All rights reserved.</p>
						</div>
					</div>
					<div class="col-sm-12 col-md-6">
						<ul class="social-icons pull-right">
							<li><a href="index.html#" target="_blank"><i class="fa fa-facebook"></i></a></li>
							<li><a href="index.html#" target="_blank"><i class="fa fa-twitter"></i></a></li>
							<li><a href="index.html#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="index.html#" target="_blank"><i class="fa fa-instagram"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- end footer -->

	<!-- Bact to top -->
	<div class="back-top">
		<a href="index.html#"><i class="fa fa-angle-up"></i></a>
	</div>

    <!-- jQuery -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>
	<script src="{% static 'js/wow.js' %}"></script>
	<script src="{% static 'js/venobox.min.js' %}"></script>
	<script src="{% static 'js/SmoothScroll.js' %}"></script>
	<script src="{% static 'js/jquery.filterizr.min.js' %}"></script>
	<script src="{% static 'js/sticky-kit.min.js' %}"></script>
	<script src="{% static 'mail/js/form-validator.min.js' %}"></script>
	<script src="{% static 'mail/js/contact-form-script.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

</body>

</html>

website/templates/about.html
{% extends 'webnav_templete.html' %}


{% block title %}
    YAKI GROUP TOURS -- HOME
{% endblock %}

{% block main %}
   <section class="inner-page-banner" style="background-image:url(img/banner/about-banner.jpg)">
		<div class="page-banner-caption">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>About Us</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="index.html">Home</a></li>
							<li class="breadcrumb-item active">About Us</li>
						</ol>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end banner -->

	<section class="section-spacing">
		<div class="container">
			<div class="row">
				<div class="col-xl-6">
					<div class="about-text wow fadeIn">
						<h2>We are YAKI GROUP TOURS</h2>
						<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos, In massa urna pellentesque habitant morbi tristique senectus.</p>
						<p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos, In massa urna pellentesque habitant morbi tristique senectus.</p>
						<ul>
							<li>We offer daily tours</li>
							<li>Best price guarantee</li>
							<li>Never lose your deposit</li>
							<li>5 star accommodations</li>
							<li>Handpicked hotels</li>
							<li>Special gifts &amp; offers for you</li>
						</ul>
					</div>
				</div>
				<div class="col-xl-6">
					<div class="about-img text-xl-right text-center wow fadeIn">
						<img class="tilt-img" src="img/about-us/1.png" alt="">
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end about -->

	<section class="section-spacing inverse-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="section-title text-center">
						<h2><span>Meet Our TEAM</span></h2>
						<p>Sorem ipsum dolor sit amet, consectetur adipisicing Suscipit votas aperiam Sorem ipsum dolor consectur adipisicing elit.</p>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-6 col-md-6 col-lg-3">
					<div class="team wow fadeIn">
						<div class="thumb">
							<img src="img/team/1.jpg" alt="">
						</div>
						<div class="team-info text-center">
							<h3>John Smith</h3>
							<h6>Tour Guide</h6>
						</div>
						<div class="team-overlay text-center">
							<h3>John Smith</h3>
							<h6>Tour Guide</h6>
							<ul class="social-icons">
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-facebook"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-twitter"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-6 col-lg-3">
					<div class="team wow fadeIn">
						<div class="thumb">
							<img src="img/team/2.jpg" alt="">
						</div>
						<div class="team-info text-center">
							<h3>Robiul Awal</h3>
							<h6>Tour Guide</h6>
						</div>
						<div class="team-overlay text-center">
							<h3>Robiul Awal</h3>
							<h6>Tour Guide</h6>
							<ul class="social-icons">
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-facebook"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-twitter"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-6 col-lg-3">
					<div class="team wow fadeIn">
						<div class="thumb">
							<img src="img/team/3.jpg" alt="">
						</div>
						<div class="team-info text-center">
							<h3>S. Davis</h3>
							<h6>Tour Guide</h6>
						</div>
						<div class="team-overlay text-center">
							<h3>S. Davis</h3>
							<h6>Tour Guide</h6>
							<ul class="social-icons">
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-facebook"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-twitter"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-6 col-lg-3">
					<div class="team wow fadeIn">
						<div class="thumb">
							<img src="img/team/4.jpg" alt="">
						</div>
						<div class="team-info text-center">
							<h3>L. Turman</h3>
							<h6>Tour Guide</h6>
						</div>
						<div class="team-overlay text-center">
							<h3>L. Turman</h3>
							<h6>Tour Guide</h6>
							<ul class="social-icons">
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-facebook"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-twitter"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-6 col-lg-3">
					<div class="team wow fadeIn">
						<div class="thumb">
							<img src="img/team/5.jpg" alt="">
						</div>
						<div class="team-info text-center">
							<h3>F. Johnson</h3>
							<h6>Tour Guide</h6>
						</div>
						<div class="team-overlay text-center">
							<h3>F. Johnson</h3>
							<h6>Tour Guide</h6>
							<ul class="social-icons">
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-facebook"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-twitter"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-6 col-lg-3">
					<div class="team wow fadeIn">
						<div class="thumb">
							<img src="img/team/6.jpg" alt="">
						</div>
						<div class="team-info text-center">
							<h3>Jesus Jackson</h3>
							<h6>Tour Guide</h6>
						</div>
						<div class="team-overlay text-center">
							<h3>Jesus Jackson</h3>
							<h6>Tour Guide</h6>
							<ul class="social-icons">
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-facebook"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-twitter"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-6 col-lg-3">
					<div class="team wow fadeIn">
						<div class="thumb">
							<img src="img/team/7.jpg" alt="">
						</div>
						<div class="team-info text-center">
							<h3>John Smith</h3>
							<h6>Tour Guide</h6>
						</div>
						<div class="team-overlay text-center">
							<h3>John Smith</h3>
							<h6>Skin Therapist</h6>
							<ul class="social-icons">
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-facebook"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-twitter"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-6 col-lg-3">
					<div class="team wow fadeIn">
						<div class="thumb">
							<img src="img/team/8.jpg" alt="">
						</div>
						<div class="team-info text-center">
							<h3>S. Davis</h3>
							<h6>Tour Guide</h6>
						</div>
						<div class="team-overlay text-center">
							<h3>S. Davis</h3>
							<h6>Tour Guide</h6>
							<ul class="social-icons">
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-facebook"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-twitter"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="about-us.html#" target="_blank"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12 text-center">
					<a href="{% url 'website:contact' %}" class="btn btn-primary">Contat Us</a>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

website/templates/contactus.html
{% extends 'webnav_templete.html' %}


{% block title %}
    YAKI GROUP TOURS -- CONTACT US
{% endblock %}

{% block main %}
    <section class="inner-page-banner" style="background-image:url(img/banner/contact-banner.jpg)">
		<div class="page-banner-caption">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>Contact Us</h1>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{% url 'website:home' %}">Home</a></li>
							<li class="breadcrumb-item active">Contact Us</li>
						</ol>
					</div>
				</div>
			</div>
		</div>
	</section>


    <section class="section-spacing">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="contact-info text-center wow fadeIn">
						<i class="fa fa-phone-square"></i>
						<h3>Make a Call</h3>
						<p><a href="tel:+61383766284">+61 3 8376 6284</a><br><a href="tel:+61383766284">+61 3 8376 6284</a></p>
					</div>
				</div>

				<div class="col-md-4">
					<div class="contact-info text-center wow fadeIn">
						<i class="fa fa-envelope-open-o"></i>
						<h3>Send a Mail</h3>
						<p><a href="mailto:info@example.com">info@example.com</a><br><a href="mailto:info@example.com">info@example.com</a></p>
					</div>
				</div>

				<div class="col-md-4">
					<div class="contact-info text-center wow fadeIn">
						<i class="fa fa-map-marker"></i>
						<h3>Find Us</h3>
						<p>123 West Street, Melbourne <br>Victoria 3000 Australia</p>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="section-title text-center">
						<h2><span>Have Any Question?</span></h2>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12 col-lg-8 offset-lg-2">
					<form id="contactForm" class="contact-form wow fadeIn" data-toggle="validator" method="post">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<input placeholder="First Name" id="fname" class="form-control" name="fname" type="text" required data-error="Please enter your first name">
									<div class="help-block with-errors"></div>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<input placeholder="Last Name" id="lname" class="form-control" name="lname" type="text">
								</div>
							</div>
						</div>
						<div class="form-group">
							<input placeholder="Email Address" id="email" class="form-control" name="email" type="email" required data-error="Please enter your valid email address">
							<div class="help-block with-errors"></div>
						</div>

						<div class="form-group">
							<textarea placeholder="Your Comments" id="message" cols="20" rows="8" class="form-control" required data-error="Please enter your comments"></textarea>
							<div class="help-block with-errors"></div>
						</div>
						<div class="text-center">
							<input value="Send Message" name="submit" class="btn btn-primary" type="submit">
							<div id="msgSubmit" class="hidden"></div>
						</div>
					</form>
				</div>

			</div>

		</div>
	</section>
	<!-- end contact -->

{% endblock %}

website/templates/destinations.html
{% extends 'webnav_templete.html' %}


{% block title %}
    YAKI GROUP TOURS -- HOME
{% endblock %}

{% block main %}
<section class="section-spacing inverse-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="section-title text-center">
						<h2><span>Popular Destination</span></h2>
						<p>Sorem ipsum dolor sit amet, consectetur adipisicing Suscipit votas aperiam Sorem ipsum dolor consectur adipisicing elit.</p>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12 col-lg-6">
					<div class="destination-item wow fadeIn">
						<a href="destination-single.html">
							<img src="img/destination/1.jpg" alt="">
                            {{ destinations.destination_name }}
							<div class="destination-info">
								<h2>Croatia</h2>
								<h3>120+ Tours</h3>
							</div>
						</a>
					</div>
				</div>
				<div class="col-md-12 col-lg-6">
					<div class="row">
						<div class="col-md-12">
							<div class="destination-item wow fadeIn">
								<a href="destination-single.html">
									<img src="img/destination/2.jpg" alt="">
									<div class="destination-info">
										<h2>Italy</h2>
										<h3>35+ Tours</h3>
									</div>
								</a>
							</div>
						</div>
						<div class="col-md-12">
							<div class="destination-item wow fadeIn">
								<a href="destination-single.html">
									<img src="img/destination/3.jpg" alt="">
									<div class="destination-info">
										<h2>Istanbul</h2>
										<h3>50+ Tours</h3>
									</div>
								</a>
							</div>
						</div>
					</div>
				</div>

			</div>

			<div class="row">
				<div class="col-md-12 col-lg-6">
					<div class="row">
						<div class="col-md-12">
							<div class="destination-item wow fadeIn">
								<a href="destination-single.html">
									<img src="img/destination/4.jpg" alt="">
									<div class="destination-info">
										<h2>Singapore</h2>
										<h3>35+ Tours</h3>
									</div>
								</a>
							</div>
						</div>
						<div class="col-md-12">
							<div class="destination-item wow fadeIn">
								<a href="destination-single.html">
									<img src="img/destination/5.jpg" alt="">
									<div class="destination-info">
										<h2>Sydney</h2>
										<h3>50+ Tours</h3>
									</div>
								</a>
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-12 col-lg-6">
					<div class="destination-item wow fadeIn">
						<a href="destination-single.html">
							<img src="img/destination/6.jpg" alt="">
							<div class="destination-info">
								<h2>Dubai</h2>
								<h3>120+ Tours</h3>
							</div>
						</a>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="text-center mt-40">
						<a href="contact-us.html" class="btn btn-primary">Contact Us</a>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}